// Generated by https://quicktype.io

export interface LoginResponse {
    userId:   string;
    userData: UserData;
}

export interface UserData {
    name:    string
    mail?:    string;
    phone:   string;
    surname: string;
    img?: string;
}


export interface LoginData {
    mail: string,
    password: string,
}
